source 'https://rubygems.org'

ruby '2.2.2', :engine => 'jruby', :engine_version => '9.0.0.0.rc2'
gem 'tdl-client-ruby', '~> 0.0.3'

gem 'minitest', '5.4.1'
gem 'minitest-reporters', '~> 1.0', '>= 1.0.19'

